export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'ICP Definition',
    description: 'Define target account tier, annual contract value (ACV) thresholds, and revenue parameters.',
    iconName: 'Target',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'BANT Calibration',
    description: 'Calibrate explicit BANT screening matrices, qualification criteria, and compliance checks.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Calibration',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Account Discovery',
    description: 'Identify active target accounts and map enterprise buying committees with verified data.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Discovery',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Budget Screening',
    description: 'Verify dedicated budget allocation, fiscal year spend, and investment authorization.',
    iconName: 'DollarSign',
    row: 2,
    col: 2,
    category: 'Budget Vetting',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Authority Verification',
    description: 'Confirm economic decision-making authority, sign-off role, and committee consensus.',
    iconName: 'UserCheck',
    row: 2,
    col: 3,
    category: 'Authority Vetting',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Need & Pain Mapping',
    description: 'Uncover acute business challenges, operational bottlenecks, and strategic imperatives.',
    iconName: 'Zap',
    row: 2,
    col: 4,
    category: 'Need Vetting',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Timeline Validation',
    description: 'Confirm project launch schedules, RFP milestones, and procurement deadlines (<90 days).',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Timeline Vetting',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'CDQA Certification',
    description: 'Cross-check audio recordings, call transcripts, and verification logs via CDQA protocols.',
    iconName: 'CheckCircle2',
    row: 3,
    col: 5,
    category: 'QA Audit',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'CRM & Calendar Injection',
    description: 'Push verified lead intelligence and booked discovery meetings seamlessly into DemandFlow Bridge™.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Handoff',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED BANT LEADS',
  badge: 'OUTCOME',
  description: 'Sales-ready enterprise prospects with confirmed budget, buying power, urgent need, and active timeline.',
}
