export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'Identify Accounts',
    description: 'Define ideal customer profiles (ICP) and curate high-fit target account lists.',
    iconName: 'Users',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Account Research',
    description: 'Deep dive into account structure, pain points, tech stacks, and buying cycles.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Intelligence',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Map Decision-Makers',
    description: 'Identify verified stakeholders, committee champions, and key budget holders.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Stakeholders',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Content & Personalize',
    description: 'Create bespoke value propositions, tailored copy, and account-specific assets.',
    iconName: 'Mail',
    row: 2,
    col: 2,
    category: 'Creative',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Multi-Channel Engage',
    description: 'Deploy synchronized outreach across email, LinkedIn, and high-impact digital touchpoints.',
    iconName: 'UserCog',
    row: 2,
    col: 3,
    category: 'Outreach',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Track Intent Signals',
    description: 'Monitor account engagement, content consumption, and first-party intent surges.',
    iconName: 'Rocket',
    row: 2,
    col: 4,
    category: 'Intent Data',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Account Qualification',
    description: 'Score stakeholder responses and validate active enterprise buying interest.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Scoring',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Create Opportunities',
    description: 'Package deep account dossiers and warm pipeline ready for sales closing.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Pipeline',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Sales Handoff',
    description: 'Seamlessly route qualified accounts directly to your sales reps with CRM sync.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Handoff',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED B2B PIPELINE',
  badge: 'OUTCOME',
  description: 'Sales-ready enterprise accounts and verified decision-makers in your pipeline.',
}
