export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'Identify',
    description: 'Identify prospects based on ICP, account fit, engagement, and buyer signals.',
    iconName: 'Users',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Segment',
    description: 'Group prospects by industry, role, behavior, interests, and buying stage.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Segmentation',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Touchpoints',
    description: 'Map multi-channel communication channels for consistent prospect reach.',
    iconName: 'Network',
    row: 2,
    col: 1,
    category: 'Channels',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Engage',
    description: 'Deliver relevant communication through appropriate, personalized channels.',
    iconName: 'Mail',
    row: 2,
    col: 2,
    category: 'Outreach',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Educate',
    description: "Provide useful information that supports the buyer's research and evaluation.",
    iconName: 'BookOpen',
    row: 2,
    col: 3,
    category: 'Nurturing',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Telemetry',
    description: 'Monitor multi-channel engagement, opens, clicks, and real-time intent telemetry.',
    iconName: 'Radio',
    row: 2,
    col: 4,
    category: 'Tracking',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Score',
    description: 'Monitor engagement and buying signals to understand sales readiness.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Lead Scoring',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Qualify',
    description: 'Identify prospects showing relevant fit, intent, and sales readiness.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Validation',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Deliver',
    description: 'Pass qualified opportunities to sales with relevant prospect intelligence.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Sales Handoff',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'SALES-READY OPPORTUNITIES',
  badge: 'OUTCOME',
  description: 'Pre-qualified, warmed decision-makers delivered directly to sales pipelines.',
}
