import {
  Rocket,
  FileText,
  CheckCircle2,
  Database,
  Send,
  Activity,
  UserCheck,
  ShieldCheck,
  Award,
  Share2,
} from 'lucide-react'

export const WORKFLOW_STAGES = [
  {
    id: 1,
    num: '01',
    title: 'Campaign Launch',
    subtitle: 'Campaign requirements, audience objectives and syndication goals activated.',
    icon: Rocket,
    accent: '#00A6FF',
    statusFrom: 'READY',
    statusTo: 'ACTIVE',
    meta: {
      campaign: 'Enterprise Cloud 2026',
      audience: 'VP & C-Suite Tech',
      region: 'North America & EMEA',
      status: 'Active',
    },
    hoverInfo: 'Triple DNS handshake (SPF, DKIM, DMARC) with automated warmup protocol.',
  },
  {
    id: 2,
    num: '02',
    title: 'Content Created',
    subtitle: 'Campaign-ready content is prepared and submitted for client review.',
    icon: FileText,
    accent: '#00A6FF',
    documents: ['Whitepaper', 'eBook', 'Case Study', 'Research'],
    meta: {
      format: 'Executive PDF Abstract',
      status: 'POC Ready',
      variants: '3 Subject Hooks',
    },
    hoverInfo: 'Senior copywriters tailor executive summaries with high-converting gated forms.',
  },
  {
    id: 3,
    num: '03',
    title: 'Client Approval',
    subtitle: 'The content is reviewed and approved before campaign execution.',
    icon: CheckCircle2,
    accent: '#10B981',
    isGreenAccent: true,
    meta: {
      review: 'Reviewing...',
      approved: 'Approved ✓',
      compliance: 'GDPR / CAN-SPAM Passed',
    },
    hoverInfo: '100% written sign-off required. Zero outreach is dispatched without client green light.',
  },
  {
    id: 4,
    num: '04',
    title: 'ICP Data Collection',
    subtitle: 'Decision-makers identified and segmented using Ideal Customer Profile.',
    icon: Database,
    accent: '#00A6FF',
    criteria: ['Industry', 'Job Title', 'Company Size', 'Geography', 'Seniority', 'Technology'],
    meta: {
      contactsPool: '10,000+ Matching',
      bounceRate: '< 1% Guaranteed',
    },
    hoverInfo: 'Live SMTP handshake verification and corporate registry cross-referencing.',
  },
  {
    id: 5,
    num: '05',
    title: 'Smart Email Distribution',
    subtitle: 'Emails distributed according to audience location and timezone.',
    icon: Send,
    accent: '#FF6D00',
    regions: [
      { code: 'AMER', time: '09:00 AM EST' },
      { code: 'EMEA', time: '09:15 AM GMT' },
      { code: 'APAC', time: '09:30 AM SGT' },
    ],
    meta: {
      delivery: '99.2% Primary Inbox',
      cadence: 'Staggered Wave',
    },
    hoverInfo: 'Dynamic volume pacing timed to executive morning business hours.',
  },
  {
    id: 6,
    num: '06',
    title: 'Engagement Tracking',
    subtitle: 'Recipient interactions monitored to identify genuine content engagement.',
    icon: Activity,
    accent: '#00A6FF',
    events: ['Delivered', 'Opened', 'Clicked', 'Downloaded'],
    activities: [
      { name: 'John Smith', action: 'Email Opened', time: '10:24 AM' },
      { name: 'Sarah Lee', action: 'CTA Clicked', time: '10:27 AM' },
      { name: 'Michael Ross', action: 'Asset Downloaded ✓', time: '10:29 AM' },
    ],
    meta: {
      signal: 'High Intent Flagged',
      score: '96/100 Intent Score',
    },
    hoverInfo: 'Cookieless telemetry tracking dwell time, link engagement, and asset opt-ins.',
  },
  {
    id: 7,
    num: '07',
    title: 'Lead Captured',
    subtitle: 'Engaged contacts converted into structured leads for evaluation.',
    icon: UserCheck,
    accent: '#00A6FF',
    leadCard: {
      name: 'Michael Ross',
      title: 'VP of Cloud Engineering',
      company: 'NexaScale Systems',
      email: 'm.ross@nexascale.io',
      region: 'North America (US-East)',
      content: 'Enterprise Cloud Migration Report',
      campaign: 'Q3 Tech Syndication',
    },
    meta: {
      type: 'Structured Lead Card',
      source: 'Content Syndication',
    },
    hoverInfo: 'Encapsulates verified corporate footprint and digital content consumption footprint.',
  },
  {
    id: 8,
    num: '08',
    title: 'Human Verification',
    subtitle: 'Our team manually validates lead accuracy, relevance and campaign eligibility.',
    icon: ShieldCheck,
    accent: '#10B981',
    checks: [
      'Valid Contact',
      'Company Match',
      'Job Title Match',
      'Industry Match',
      'Location Match',
      'ICP Match',
      'Contact Details',
    ],
    meta: {
      decision: 'YES → Qualified',
      rejected: 'NO → Rejected (Muted)',
    },
    hoverInfo: '100% human phone verification of active employment and direct-dial reachability.',
  },
  {
    id: 9,
    num: '09',
    title: 'Qualified Lead',
    subtitle: 'Verified contacts matching agreed criteria become qualified leads.',
    icon: Award,
    accent: '#10B981',
    badges: ['Verified', 'ICP Match', 'Engagement Confirmed'],
    meta: {
      status: 'QUALIFIED LEAD',
      tier: '100% Sales-Qualified SQL',
    },
    hoverInfo: 'Certified high-converting prospect ready for immediate sales conversation.',
  },
  {
    id: 10,
    num: '10',
    title: 'Client Delivery',
    subtitle: 'Qualified leads securely delivered for sales follow-up.',
    icon: Share2,
    accent: '#00A6FF',
    meta: {
      destination: 'Client CRM / Webhook',
      status: 'Delivery Complete ✓',
      outreach: 'Ready for Outreach',
    },
    hoverInfo: 'Automated CRM integration (Salesforce, HubSpot) with full context notes.',
  },
]
