export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'Define ICP & Criteria',
    description: 'Define ICP, target accounts, roles, and mandatory qualification criteria.',
    iconName: 'Users',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Identify Decision-Makers',
    description: 'Find relevant companies and verified decision-makers across target sectors.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Discovery',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Content Syndication',
    description: 'Distribute targeted whitepapers, analyst briefs, and high-value digital assets.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Distribution',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Engage & Track Interest',
    description: 'Capture prospect engagement, asset downloads, and active buyer interest.',
    iconName: 'Mail',
    row: 2,
    col: 2,
    category: 'Engagement',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Intent Surge Signals',
    description: 'Validate first-party & third-party intent surges and active category research.',
    iconName: 'UserCog',
    row: 2,
    col: 3,
    category: 'Intent Data',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Score Fit & Intent',
    description: 'Evaluate fit, engagement depth, and intent signals via DemandFlow Bridge.',
    iconName: 'Rocket',
    row: 2,
    col: 4,
    category: 'Scoring',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Qualify Against SLA',
    description: 'Validate prospects against pre-agreed qualification and budget criteria.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Screening',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Data Hygiene & Audit',
    description: 'Execute triple-layer SMTP validation, direct dials, and consent verification.',
    iconName: 'UserCheck',
    row: 3,
    col: 3.5,
    category: 'Validation',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Deliver Sales-Ready MQLs',
    description: 'Provide sales-ready MQLs with prospect intelligence direct to your CRM.',
    iconName: 'RefreshCw',
    row: 3,
    col: 5,
    category: 'Delivery',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED MQL LEADS',
  badge: 'OUTCOME',
  description: 'Sales-ready, verified decision-makers delivered directly to your pipeline.',
}
