export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'ICP & Sales Goals',
    description: 'Define ideal customer profiles, target industries, ACV thresholds, and qualification criteria.',
    iconName: 'Building2',
    row: 1,
    col: 2,
    category: 'Strategy',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Criteria Calibration',
    description: 'Calibrate explicit SQL qualification rubrics, lead scoring models, and compliance checks.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Calibration',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Account Discovery',
    description: 'Identify high-fit target accounts and map buying committees with verified executive contact data.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Data Discovery',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Prospect Research',
    description: 'Analyze technographic fit, competitor installs, organizational challenges, and intent signals.',
    iconName: 'Search',
    row: 2,
    col: 2,
    category: 'Intelligence',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Multi-Touch Outreach',
    description: 'Deploy personalized omnichannel outreach across executive email, direct phone, and social cadences.',
    iconName: 'Mail',
    row: 2,
    col: 3,
    category: 'Engagement',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Intent & Need Probing',
    description: 'Conduct structured discovery conversations to evaluate acute operational bottlenecks and project urgency.',
    iconName: 'Zap',
    row: 2,
    col: 4,
    category: 'Need Vetting',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Sales Readiness Check',
    description: 'Validate budget allocation, signing authority, and active purchasing milestones (<90 days).',
    iconName: 'Clock',
    row: 2,
    col: 5,
    category: 'Validation',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'CDQA Quality Audit',
    description: 'Cross-check call audio, transcripts, and qualification records against agreed-upon sales standards.',
    iconName: 'SearchCheck',
    row: 3,
    col: 5,
    category: 'QA Audit',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'CRM & Calendar Sync',
    description: 'Inject verified SQL dossiers and booked meetings seamlessly into DemandFlow Bridge™.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Handoff',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED SQL LEADS',
  badge: 'OUTCOME',
  description: 'Sales-ready, high-intent enterprise prospects delivered directly into your pipeline.',
}
