export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'Database Audit',
    description: 'Diagnose decay percentages, syntax anomalies, and duplicate clusters.',
    iconName: 'Database',
    row: 1,
    col: 2,
    category: 'Assessment',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Syntax Normalization',
    description: 'Standardize international phone numbers, state codes, and email schemas.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Sanitization',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Fuzzy Deduplication',
    description: 'Merge duplicate records while preserving complete sales activity logs.',
    iconName: 'UserCog',
    row: 2,
    col: 1,
    category: 'Consolidation',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Live SMTP Ping',
    description: 'Direct handshake ping verifies mailbox existence with zero emails sent.',
    iconName: 'Mail',
    row: 2,
    col: 2,
    category: 'Deliverability',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Trap Suppression',
    description: 'Purge known honeypots, spam traps, and toxic catch-all server domains.',
    iconName: 'Rocket',
    row: 2,
    col: 3,
    category: 'Protection',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Turnover Detection',
    description: 'Identify departed executives and discover incoming replacement buyers.',
    iconName: 'RefreshCw',
    row: 2,
    col: 4,
    category: 'Employment',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Direct Dial Append',
    description: 'Append verified direct desk extensions, mobile numbers, and LinkedIn URLs.',
    iconName: 'Users',
    row: 2,
    col: 5,
    category: 'Enrichment',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Quality Scoring QA',
    description: 'Rigorous multi-layer validation guaranteeing 99%+ database health score.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Validation',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'CRM Restore & Sync',
    description: 'Native bi-directional synchronization directly into Salesforce or HubSpot.',
    iconName: 'LineChart',
    row: 3,
    col: 3.5,
    category: 'Restoration',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'PRISTINE 99%+ HEALTH CRM',
  badge: 'OUTCOME',
  description: 'Sub-1% bounce rate, zero duplicate bloat, and verified decision maker dials.',
}
