export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'ICP & Audience',
    description: 'Identify ideal customer profiles, industries, roles, and target accounts.',
    iconName: 'Users',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Campaign Strategy',
    description: 'Define messaging, offers, personalization, cadence, and campaign goals.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Strategy',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Data & Segmentation',
    description: 'Build, verify, clean, and segment relevant B2B contact lists.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Data & List',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Email Creation',
    description: 'Create persuasive, brand-aligned email copy, CTAs, and responsive templates.',
    iconName: 'Mail',
    row: 2,
    col: 2,
    category: 'Creative',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Personalization',
    description: 'Tailor messaging by persona, industry, intent, account, and buyer stage.',
    iconName: 'UserCog',
    row: 2,
    col: 3,
    category: 'Relevance',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Campaign Launch',
    description: 'Schedule and deploy targeted email campaigns across selected segments.',
    iconName: 'Rocket',
    row: 2,
    col: 4,
    category: 'Deployment',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Engagement Tracking',
    description: 'Monitor opens, clicks, replies, bounces, and engagement signals.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Analytics',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Lead Qualification',
    description: 'Identify engaged prospects and prioritize leads based on response and intent.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Validation',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Optimize & Nurture',
    description: 'A/B test, refine messaging, retarget, and nurture prospects through the funnel.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Optimization',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED B2B LEADS',
  badge: 'OUTCOME',
  description: 'Sales ready, verified decision makers delivered directly to your pipeline.',
}
