import {
  Target,
  Search,
  MessageCircle,
  MousePointerClick,
  BadgeCheck,
  CalendarCheck,
  TrendingUp,
  RefreshCw,
  Clock,
  Sparkles,
  HelpCircle,
  CheckCircle2,
  Award,
} from 'lucide-react'

export const WORKFLOW_PHASES = [
  { id: 'define', num: '01', name: 'Define', activeIndex: 0 },
  { id: 'identify', num: '02', name: 'Identify', activeIndex: 1 },
  { id: 'engage', num: '03', name: 'Engage', activeIndex: 2 },
  { id: 'capture', num: '04', name: 'Capture', activeIndex: 3 },
  { id: 'qualify', num: '05', name: 'Qualify', activeIndex: 5 },
  { id: 'convert', num: '06', name: 'Convert', activeIndex: 8 },
]

export const WORKFLOW_NODES = [
  {
    id: 'define',
    number: '01',
    type: 'process',
    title: 'Define Target Market',
    tag: 'TARGETING',
    shortDesc: 'Build a focused ICP based on industry, company size, role and buying intent.',
    fullDesc: 'We establish granular firmographic and technographic filters (headcount, revenue, tech stack, regional compliance) to ensure outbound efforts only target high-value accounts.',
    icon: Target,
    accent: '#00A6FF',
    accentType: 'primary',
  },
  {
    id: 'identify',
    number: '02',
    type: 'process',
    title: 'Identify Ideal Prospects',
    tag: 'SOURCING',
    shortDesc: 'Source decision-makers and verify direct dials with live SMTP handshakes.',
    fullDesc: 'Every decision-maker record undergoes real-time SMTP ping validation, corporate registry checks, and phone verification to guarantee < 1% bounce rate.',
    icon: Search,
    accent: '#00A6FF',
    accentType: 'primary',
  },
  {
    id: 'engage',
    number: '03',
    type: 'process',
    title: 'Engage Decision Makers',
    tag: 'OUTREACH',
    shortDesc: 'Deploy personalized multi-touch email cadences timed to local business hours.',
    fullDesc: 'Custom executive copywriting tailored to VP and C-level pain points, dispatched across secondary warmed domains to ensure 99%+ primary inbox placement.',
    icon: MessageCircle,
    accent: '#FF6D00',
    accentType: 'accent',
  },
  {
    id: 'capture',
    number: '04',
    type: 'process',
    title: 'Capture Response',
    tag: 'TELEMETRY',
    shortDesc: 'Track opens, link clicks, dwell time, and gated asset downloads in real time.',
    fullDesc: 'High-intent behavioral telemetry monitors content consumption. Explicit actions (such as downloading a whitepaper) trigger immediate lead conversion flags.',
    icon: MousePointerClick,
    accent: '#00A6FF',
    accentType: 'primary',
  },
  {
    id: 'decision-1',
    number: '05',
    type: 'decision',
    title: 'Is the Prospect Engaged?',
    shortDesc: 'Evaluate explicit open, click, or asset download actions.',
    yesText: 'YES — Active Interest',
    noText: 'NO — Not Yet Engaged',
    icon: HelpCircle,
    accent: '#FFA600',
    accentType: 'highlight',
  },
  {
    id: 'qualify',
    number: '06',
    type: 'process',
    title: 'Qualify the Lead',
    tag: 'VERIFICATION',
    shortDesc: '100% human phone verification of role authority, company match, and relevance.',
    fullDesc: 'Dedicated QA analysts cross-reference active LinkedIn employment, call corporate switchboards, and confirm project relevance before passing the lead.',
    icon: BadgeCheck,
    accent: '#72D669',
    accentType: 'success',
  },
  {
    id: 'decision-2',
    number: '07',
    type: 'decision',
    title: 'Meets Qualification Criteria?',
    shortDesc: 'Assess budget, authority, ICP parameters and explicit consent.',
    yesText: 'YES — Verified SQL',
    noText: 'NO — Needs More Nurturing',
    icon: HelpCircle,
    accent: '#FFA600',
    accentType: 'highlight',
  },
  {
    id: 'sales-ready',
    number: '08',
    type: 'success',
    title: 'Sales-Ready Opportunity',
    tag: 'QUALIFIED',
    shortDesc: 'Confirmed purchase intent, verified direct dial, and complete buyer dossier.',
    fullDesc: 'The prospect meets all agreed client requirements. Complete dossier packaged with engagement timestamps, direct dial, and context notes.',
    icon: Award,
    accent: '#72D669',
    accentType: 'success',
  },
  {
    id: 'appointment',
    number: '09',
    type: 'process',
    title: 'Appointment / Sales Handoff',
    tag: 'DISPATCH',
    shortDesc: 'Direct CRM sync via webhook and scheduled SDR-to-AE introduction meeting.',
    fullDesc: 'Instant synchronization with Salesforce, HubSpot, or custom webhook endpoints to allow sales executives to engage warm prospects immediately.',
    icon: CalendarCheck,
    accent: '#00A6FF',
    accentType: 'primary',
  },
  {
    id: 'pipeline',
    number: '10',
    type: 'conversion',
    title: 'Pipeline Opportunity',
    tag: 'REVENUE',
    shortDesc: 'High-confidence sales pipeline entered with verified buyer interest.',
    fullDesc: 'Measurable B2B sales pipeline generation with guaranteed replacement warranty on any invalid records.',
    icon: TrendingUp,
    accent: '#FF6D00',
    accentType: 'conversion',
  },
]

// Alternative & Nurture Return Loop Nodes
export const NURTURE_NODES = {
  nurture1: {
    id: 'nurture-1',
    badge: 'NURTURE LOOP A',
    title: 'Not Engaged',
    step1: 'Nurture & Re-Engage',
    step2: 'Revisit Prospect',
    desc: 'Automated 30-day re-engagement sequence with new educational angles and industry insights.',
    icon: RefreshCw,
  },
  nurture2: {
    id: 'nurture-2',
    badge: 'NURTURE LOOP B',
    title: 'Needs More Nurturing',
    step1: 'Lead Nurturing Cadence',
    step2: 'Re-Qualify on Intent',
    desc: 'Targeted case-study delivery to keep solution top-of-mind until timing or budget aligns.',
    icon: Clock,
  },
}
