export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'ICP & TAM Definition',
    description: 'Identify ideal customer profiles, target account lists (TAL), industries, and buying centers.',
    iconName: 'Building2',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Demand Strategy',
    description: 'Define multi-channel messaging, content assets, offer architecture, and conversion goals.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Strategy',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Account & Intent Mapping',
    description: 'Enrich verified decision-maker records, track intent signals, and segment in-market buyers.',
    iconName: 'Network',
    row: 2,
    col: 1,
    category: 'Data & Intent',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Content & Offer Creation',
    description: 'Develop high-value research, whitepapers, interactive assets, and high-impact email copy.',
    iconName: 'FileText',
    row: 2,
    col: 2,
    category: 'Creative',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Omnichannel Cadence',
    description: 'Personalize touches across email, LinkedIn, content syndication, and digital touchpoints.',
    iconName: 'Share2',
    row: 2,
    col: 3,
    category: 'Relevance',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Multi-Channel Launch',
    description: 'Orchestrate synchronized campaign deployment across all selected audience cohorts.',
    iconName: 'Rocket',
    row: 2,
    col: 4,
    category: 'Deployment',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Engagement & Telemetry',
    description: 'Track multi-touch content downloads, view duration, replies, and buyer intent signals.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Analytics',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'BANT Lead Qualification',
    description: 'Verify budget, authority, need, timeline, and firmographic fit before sales handoff.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Validation',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Pipeline Acceleration',
    description: 'Automate retargeting, continuous nurturing, and direct CRM sync for sales conversations.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Optimization',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED B2B PIPELINE',
  badge: 'OUTCOME',
  description: 'Sales-ready, verified buying committees delivered directly to your pipeline.',
}
