export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'ICP & Account Mapping',
    description: 'Define exact ICP parameters, target industries, revenue tiers, and account lists.',
    iconName: 'Building2',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Decision-Maker Matrix',
    description: 'Map buying committees across C-suite, VPs, and budget-holding directors.',
    iconName: 'Users',
    row: 1,
    col: 4,
    category: 'Stakeholders',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Data & Telephony Cleanse',
    description: 'Triple-verify corporate inboxes, direct dials, and purge bounced domains.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Data Quality',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Pain-Centric Content',
    description: 'Syndicate category-specific research briefs, whitepapers, and problem assets.',
    iconName: 'FileText',
    row: 2,
    col: 2,
    category: 'Engagement',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Intent & Engagement Surge',
    description: 'Measure content consumption depth, reading time, and topic surge telemetry.',
    iconName: 'Zap',
    row: 2,
    col: 3,
    category: 'Intent Data',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Discovery Screening Q&A',
    description: 'Collect bespoke answers to 2-4 qualification questions on stack, pain & timeline.',
    iconName: 'ClipboardCheck',
    row: 2,
    col: 4,
    category: 'Discovery',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Human QA Audit',
    description: 'Rigorous manual review validating authority, response accuracy, and phone dials.',
    iconName: 'SearchCheck',
    row: 2,
    col: 5,
    category: 'Validation',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'CRM Lead Enrichment',
    description: 'Deliver rich lead dossiers with verified dials, emails, and verbatim intel to CRM.',
    iconName: 'FolderCheck',
    row: 3,
    col: 5,
    category: 'CRM Handoff',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Pipeline Calibration',
    description: 'Calibrate ICP scoring using SDR feedback with zero-bounce replacement SLA.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Optimization',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'SALES-READY HQLS',
  badge: 'OUTCOME',
  description: 'Pre-qualified, high-intent B2B decision-makers delivered directly to your pipeline.',
}
