export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'ICP & Asset Selection',
    description: 'Identify ideal customer profiles, asset themes, and target account lists.',
    iconName: 'Compass',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Syndication Strategy',
    description: 'Define distribution channels, delivery pacing, screening criteria, and CPL goals.',
    iconName: 'ListChecks',
    row: 1,
    col: 4,
    category: 'Strategy',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Publisher Mapping',
    description: 'Map target accounts against verified B2B media networks and publishing hubs.',
    iconName: 'Globe',
    row: 2,
    col: 1,
    category: 'Network',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Asset Gating',
    description: 'Gate authoritative whitepapers and reports behind customized opt-in capture forms.',
    iconName: 'FileText',
    row: 2,
    col: 2,
    category: 'Capture',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Personalization',
    description: 'Tailor content recommendations by job role, industry vertical, and buying stage.',
    iconName: 'UserCog',
    row: 2,
    col: 3,
    category: 'Relevance',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Content Distribution',
    description: 'Deploy assets across specialized tech portals, executive newsletters, and feeds.',
    iconName: 'Rocket',
    row: 2,
    col: 4,
    category: 'Deployment',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Reader Tracking',
    description: 'Monitor downloads, read time, reader verification, and content engagement signals.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Analytics',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Lead Qualification',
    description: 'Verify job titles, review custom screening answers, and score purchase intent.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Validation',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Validation & Delivery',
    description: 'SMTP verify corporate domains, remove invalid contacts, and sync directly to CRM.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Delivery',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED B2B LEADS',
  badge: 'OUTCOME',
  description: 'Verified, high-intent prospects delivered directly to your pipeline.',
}
