export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'Target',
    description: 'Identify accounts and decision-makers that match your ICP.',
    iconName: 'Users',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Research',
    description: 'Understand account context, roles, business needs, and relevant signals.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Intelligence',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Verified Data',
    description: 'Source triple-verified direct dials, corporate email inboxes, and buyer profiles.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Data Hygiene',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Qualify',
    description: 'Evaluate prospect fit, engagement, need, and sales readiness.',
    iconName: 'Search',
    row: 2,
    col: 2,
    category: 'Scoring',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Engage',
    description: 'Reach prospects through relevant and personalized outreach.',
    iconName: 'Mail',
    row: 2,
    col: 3,
    category: 'Outreach',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Connect',
    description: 'Start meaningful conversations with qualified prospects.',
    iconName: 'Zap',
    row: 2,
    col: 4,
    category: 'Conversation',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Vetting',
    description: 'Confirm buying authority, budget allocation, and purchasing urgency.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Validation',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'CDQA Audit',
    description: 'Independent quality audit verifying attendee consent and recorded notes.',
    iconName: 'CheckCircle2',
    row: 3,
    col: 5,
    category: 'QA Audit',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Book',
    description: 'Schedule relevant sales appointments with the right stakeholders.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Scheduling',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'DELIVER QUALIFIED MEETINGS',
  badge: 'OUTCOME',
  description: 'Provide meeting details and relevant prospect intelligence to your sales team.',
}
