export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'Define & Strategy',
    description: 'Set webinar goals, target audience, ICP, industries, roles, and campaign objectives.',
    iconName: 'Compass',
    row: 1,
    col: 2,
    category: 'Strategy',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Target Audience',
    description: 'Identify relevant companies and decision-makers who match the campaign audience.',
    iconName: 'Users',
    row: 1,
    col: 4,
    category: 'Audience',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Multi-Channel Promote',
    description: 'Promote the webinar through targeted B2B outreach, email cadences, and social channels.',
    iconName: 'Mail',
    row: 2,
    col: 1,
    category: 'Promotion',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Generate Registrations',
    description: 'Capture verified signups from relevant prospects and high-priority buying committees.',
    iconName: 'Database',
    row: 2,
    col: 2,
    category: 'Registration',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Attendee Engagement',
    description: 'Connect prospects with high-value sessions and capture live interaction & Q&A data.',
    iconName: 'UserCog',
    row: 2,
    col: 3,
    category: 'Engagement',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Track Intent Signals',
    description: 'Monitor attendee participation time, questions asked, polls, and intent surges.',
    iconName: 'Rocket',
    row: 2,
    col: 4,
    category: 'Analytics',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Lead Qualification',
    description: 'Evaluate attendee engagement data based on firmographic fit, interest, and buying signals.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Qualification',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Prospect Intelligence',
    description: 'Package deep attendee intelligence dossiers with interaction context for sales.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Intelligence',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Sales Handoff',
    description: 'Provide sales-ready leads directly to your sales reps with instant CRM sync.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Handoff',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'QUALIFIED WEBINAR PIPELINE',
  badge: 'OUTCOME',
  description: 'Verified, sales-ready decision-makers delivered directly to your pipeline.',
}
