export const WORKFLOW_STEPS = [
  {
    id: '01',
    stepNumber: '01',
    title: 'ICP & TAM Criteria',
    description: 'Define ideal customer profile, industries, company size, and audience criteria.',
    iconName: 'Users',
    row: 1,
    col: 2,
    category: 'Targeting',
  },
  {
    id: '02',
    stepNumber: '02',
    title: 'Account Identification',
    description: 'Identify relevant target accounts, companies, and organizations matching criteria.',
    iconName: 'Compass',
    row: 1,
    col: 4,
    category: 'Discovery',
  },
  {
    id: '03',
    stepNumber: '03',
    title: 'Stakeholder Mapping',
    description: 'Pinpoint key decision-makers, buying committees, and executive roles.',
    iconName: 'Database',
    row: 2,
    col: 1,
    category: 'Research',
  },
  {
    id: '04',
    stepNumber: '04',
    title: 'Contact Discovery',
    description: 'Uncover corporate emails, direct phone dials, and executive LinkedIn profiles.',
    iconName: 'Mail',
    row: 2,
    col: 2,
    category: 'Intelligence',
  },
  {
    id: '05',
    stepNumber: '05',
    title: 'Multi-Step Validation',
    description: 'Perform real-time SMTP ping, syntax validation, and zero-bounce verification.',
    iconName: 'UserCog',
    row: 2,
    col: 3,
    category: 'Validation',
  },
  {
    id: '06',
    stepNumber: '06',
    title: 'Data Enrichment',
    description: 'Append firmographics, technographics, funding stages, and revenue metrics.',
    iconName: 'Rocket',
    row: 2,
    col: 4,
    category: 'Enrichment',
  },
  {
    id: '07',
    stepNumber: '07',
    title: 'Audience Segmentation',
    description: 'Organize and segment records by industry vertical, territory, and seniority.',
    iconName: 'LineChart',
    row: 2,
    col: 5,
    category: 'Segmentation',
  },
  {
    id: '08',
    stepNumber: '08',
    title: 'Quality Verification',
    description: 'Execute final multi-point verification and compliance checks.',
    iconName: 'UserCheck',
    row: 3,
    col: 5,
    category: 'Verification',
  },
  {
    id: '09',
    stepNumber: '09',
    title: 'Campaign-Ready Delivery',
    description: 'Deliver structured, verified lists formatted for seamless CRM integration.',
    iconName: 'RefreshCw',
    row: 3,
    col: 3.5,
    category: 'Delivery',
  },
]

export const TARGET_GOAL = {
  id: 'goal',
  title: 'CAMPAIGN-READY B2B LISTS',
  badge: 'OUTCOME',
  description: '100% verified, high-accuracy prospect data delivered to your pipeline.',
}
